-- schema.sql
-- Run this once against your Neon database before seeding.
--
-- KEY DESIGN DECISIONS (explained because these matter for the interview):
--
-- 1. id is a UUID generated by the app (not serial), but more importantly,
--    we ALSO keep created_at, which is set once at insert time and NEVER
--    changes. This is what we paginate on. updated_at changes on edits,
--    so it cannot be used for stable pagination (a row that gets updated
--    would "jump" to the top of an updated_at-sorted feed and you'd see it
--    twice, or worse, never see a row that was pushed down past your cursor).
--
-- 2. Composite index on (created_at DESC, id DESC) is what makes
--    "newest first" pagination fast. Without it, every page after the
--    first does a full sort of 200k rows. With it, Postgres walks the
--    index directly to find the next page - no sorting needed at all.
--
-- 3. category has its own index because the most common access pattern is
--    "newest products in category X". We use a composite index
--    (category, created_at DESC, id DESC) for that case specifically,
--    so filtered pagination is just as fast as unfiltered.

CREATE TABLE IF NOT EXISTS products (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Needed for gen_random_uuid() on some Postgres versions / Neon images.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Powers: "give me the next page of ALL products, newest first"
CREATE INDEX IF NOT EXISTS idx_products_created_id
    ON products (created_at DESC, id DESC);

-- Powers: "give me the next page of products IN CATEGORY X, newest first"
CREATE INDEX IF NOT EXISTS idx_products_category_created_id
    ON products (category, created_at DESC, id DESC);

-- Lets the UI populate a category filter dropdown quickly.
CREATE INDEX IF NOT EXISTS idx_products_category
    ON products (category);
